# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: 7d76849d34456615405509c9e75395bfcc84d1c95c43078f9126749c4a0a2eb66c5801dc46eb4d45f91479ca0d2ed185471727f8613be4c0ebb73c89eaaf94b2

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
